apiVersion: v1
kind: Service
metadata:
  name: forecast-api
  namespace: demand-forecast
  labels:
    app: forecast-api
spec:
  type: ClusterIP
  selector:
    app: forecast-api
  ports:
    - name: http
      port: 8000
      targetPort: http
